version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile
  slack:     circleci/slack@3

executors:
  default:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/app

jobs:
  build:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"
      - run: bundle exec rspec
      - run:
          name: generate_ical (dry run)
          command: |
            bundle exec rake generate_ical
            git --no-pager diff
      - slack/notify-on-failure

  update_ical:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"
      - run: .circleci/update_ical.sh
      - slack/notify-on-failure

workflows:
  version: 2

  build:
    jobs:
      - build
      - update_ical:
          requires:
            - build
          filters:
            branches:
              only: master

  update_new_year:
    triggers:
      - schedule:
          cron: "0 0 1 1 *"
          filters:
            branches:
              only: master

    jobs:
      - update_ical
