title: "KING OF PRISM"
characters:
  - name:        "神浜コウジ"
    birthday:    "1/14"

  - name:        "速水ヒロ"
    birthday:    "10/10"

  - name:        "仁科カヅキ"
    birthday:    "5/5"

  - name:        "一条シン"
    birthday:    "2/29"

  - name:        "太刀花ユキノジョウ"
    birthday:    "7/9"

  - name:        "香賀美タイガ"
    birthday:    "5/4"

  - name:        "十王院カケル"
    birthday:    "12/22"

  - name:        "鷹梁ミナト"
    birthday:    "8/21"

  - name:        "西園寺レオ"
    birthday:    "4/4"

  - name:        "涼野ユウ"
    birthday:    "3/14"

  - name:        "山田リョウ"
    birthday:    "9/24"
    description: "清掃の日"

  - name:        "氷室聖"
    birthday:    "11/23"

  - name:        "黒川冷（DJ.Coo）"
    birthday:    "8/8"

  - name:        "如月ルヰ"
    birthday:    "2/29"

  - name:        "大和アレクサンダー"
    birthday:    "6/6"

  - name:        "法月仁"
    birthday:    "7/18"

  - name:        "高田馬場ジョージ"
    birthday:    "9/15"

  - name:        "鶯谷モンド"
    birthday:    "7/11"

  - name:        "五反田ココロ"
    birthday:    "10/15"

  - name:        "神田ミツバ"
    birthday:    "3/1"

  - name:        "御徒町ツルギ"
    birthday:    "11/1"

  - name:        "池袋エィス"
    birthday:    "4/1"

  - name:        "天下左京"
    birthday:    "11/25"

  - name:        "天下右京"
    birthday:    "11/25"
