title: "ワッチャプリマジ！"
characters:
  - name:        "陽比野まつり"
    birthday:    "8/8"

  - name:        "弥生ひな"
    birthday:    "3/27"

  - name:        "心愛れもん"
    birthday:    "11/28"

  - name:        "皇あまね"
    birthday:    "6/2"

  - name:        "甘瓜みるき"
    birthday:    "9/10"

  - name:        "みゃむ"
    birthday:    "8/8"

  - name:        "チムム"
    birthday:    "7/9"

  - name:        "きゃろん"
    birthday:    "2/10"

  - name:        "ぱたの"
    birthday:    "5/5"

  - name:        "はにたん"
    birthday:    "12/29"

  - name:        "御芽河あうる"
    birthday:    "4/28"

  - name:        "ジェニファー・純恋・ソル"
    birthday:    "7/17"
