title: "プリパラ"
characters:
  # プリパラ Season1
  - name:        "真中らぁら"
    birthday:    "11/20"
    description: "ピザの日"

  - name:        "南みれぃ"
    birthday:    "10/1"
    description: "法の日、メガネの日"

  - name:        "北条そふぃ"
    birthday:    "7/30"
    description: "梅干しの日"

  - name:        "東堂シオン"
    birthday:    "1/5"
    description: "囲碁の日"

  - name:        "ドロシー・ウェスト"
    birthday:    "2/5"
    description: "ふたごの日"

  - name:        "レオナ・ウェスト"
    birthday:    "2/5"
    description: "ふたごの日"

  - name:        "真中のん"
    birthday:    "9/6"
    description: "妹の日"

  - name:        "北条コスモ"
    birthday:    "9/12"
    description: "宇宙の日"

  - name:        "愛媛なお"
    birthday:    "11/20"
    description: "らぁらと同じ日"

  - name:        "鍋島ちゃん子"
    birthday:    "12/28"
    description: "相撲の日"

  # プリパラ Season2
  - name:        "黒須あろま"
    birthday:    "6/6"
    description: "悪魔の日"

  - name:        "白玉みかん"
    birthday:    "10/4"
    description: "天使の日"

  - name:        "ガァルル"
    birthday:    "4/17"
    description: "怪獣の日、恐竜の日"

  - name:        "紫京院ひびき"
    birthday:    "3/27"
    description: "世界演劇の日"

  - name:        "ファルル"
    birthday:    "3/21"
    description: "ファルル目覚めの日"

  - name:        "緑風ふわり"
    birthday:    "8/11"
    description: "山の日"

  - name:        "黄木あじみ"
    birthday:    "11/3"
    description: "文化の日"

  # プリパラ Season3
  - name:        "月川ちり"
    birthday:    "11/15"
    description: "きものの日"

  - name:        "太陽ペッパー"
    birthday:    "2/9"
    description: "肉の日"

  - name:        "ジュリィ"
    birthday:    "7/10"
    description: "初めてプリチケが届いた日（プリパラ筐体の稼働開始日）"

  - name:        "ジャニス"
    birthday:    "7/10"
    description: "初めてプリチケが届いた日（プリパラ筐体の稼働開始日）"

  - name:     "じゅのん"
    birthday: "1/23"

  - name:     "ぴのん"
    birthday: "2/13"

  - name:     "かのん"
    birthday: "3/21"

  # アイドルタイムプリパラ
  - name:        "夢川ゆい"
    birthday:    "8/18"
    description: "米の日"

  - name:        "虹色にの"
    birthday:    "3/14"
    description: "円周率の日、数学の日"

  - name:        "幸多みちる"
    birthday:    "7/13"
    description: "オカルトの日"

  - name:        "華園しゅうか"
    birthday:    "10/17"
    description: "貯蓄の日"

  - name:        "ガァララ・ス・リープ"
    birthday:    "6/10"
    description: "時の記念日"

  - name:        "ファララ・ア・ラーム"
    birthday:    "6/10"
    description: "時の記念日"

  - name:        "夢川ショウゴ"
    birthday:    "11/23"
    description: "いい兄さんの日"

  - name:        "三鷹アサヒ"
    birthday:    "1/1"
    description: "初日の日"

  - name:        "高瀬コヨイ"
    birthday:    "12/24"
    description: "クリスマス・イヴ"

  - name:        "華園みあ"
    birthday:    "3/9"
    description: "上葉みあのモデルとなったPrizmmy☆の日下部美愛の誕生日と同一"

  - name:        "地獄ミミ子"
    birthday:    "1/16"
    description: "閻魔の日、初閻魔"

  # アイドルランドプリパラ
  - name:        "香田澄あまり"
    birthday:    "2/29"
    description: "うるう日"

  - name:        "ウシミツ"
    birthday:    "2/22"
    description: "忍者の日"

  - name:        "大江戸シンヤ"
    birthday:    "9/9"
    description: "温泉の日"

  - name:        "マリオ"
    birthday:    "2/29"
    description: "うるう日"

  - name:        "ポォロロ"
    birthday:    "7/3"
    description: "涙の日"

  # 大プリパラ展
  - name:        "らぁるる"
    birthday:    "5/5"
    description: "未来の日"
